spring:
    session:
        store-type: jdbc
        jdbc:
            initialize-schema: always
            table-name: spring_session
    datasource:
        url: jdbc:mysql://localhost:3306/db_practise_16
        username: root
        password: 12345678
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update